apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.secrets.DB_HOST }}
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: {{ .Values.secrets.DB_PORT }}
    targetPort: {{ .Values.secrets.DB_PORT }}