apiVersion: v1
kind: Service
metadata:
  annotations:
      service.beta.kubernetes.io/do-loadbalancer-certificate-id: {{ .Values.secrets.CERTIFICATE_ID }}
      service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
  labels:
    app: algova-django-api
  name: algova-django-api-service
  namespace: default
spec:
  ports:
  - name: algova-django-api-port
    nodePort: 30050
    port: 80
    protocol: TCP
    targetPort: 8000
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8000
  selector:
    app: algova-django-api
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: algova-django-api-sa
  namespace: {{ .Release.Namespace }}