apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DJANGO_ALLOWED_HOSTS: {{ .Values.secrets.DJANGO_ALLOWED_HOSTS | b64enc }}
  SECRET_KEY: {{ .Values.secrets.DJANGO_SECRET_KEY | b64enc }}
  DJANGO_SETTINGS_MODULE: {{ .Values.secrets.DJANGO_SETTINGS_MODULE | b64enc }}
  AWS_STORAGE_BUCKET_NAME: {{ .Values.secrets.AWS_STORAGE_BUCKET_NAME | b64enc }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.AWS_ACCESS_KEY_ID | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.AWS_SECRET_ACCESS_KEY | b64enc }}
  AWS_DEFAULT_REGION: {{ .Values.secrets.AWS_DEFAULT_REGION | b64enc }}
  DB_NAME: {{ .Values.secrets.DB_NAME | b64enc }}
  DB_USER: {{ .Values.secrets.DB_USER | b64enc }}
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | b64enc }}
  DB_HOST: {{ .Values.secrets.DB_HOST | b64enc }}
  DB_PORT: {{ .Values.secrets.DB_PORT | b64enc }}