kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: algova-django-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: algova-django-api
  template:
    metadata:
      labels:
        app: algova-django-api
    spec:
      serviceAccountName: algova-django-api-sa
      containers:
      - name: algova-django-api
        image: {{ .Values.secrets.DOCKER_REGISTRY }}/algova-django-api:latest
        imagePullPolicy: Always
        command: ['gunicorn', 'demo.wsgi', '--bind=0.0.0.0:8000', '--log-level=debug']
        envFrom:
        - secretRef:
            name: api-secrets
        - configMapRef:
            name: api-configmap
        resources:
          requests:
            memory: "300Mi"
            cpu: "150m"
          limits:
            memory: "600Mi"
            cpu: "450m"