apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DJANGO_ALLOWED_HOSTS: {{ .Values.DJANGO_ALLOWED_HOSTS | b64enc }}
  SECRET_KEY: {{ .Values.SECRET_KEY | b64enc }}